// GENERATED by scripts/build-icons.mjs — do not edit by hand.
// Source: Hue Icons (Figma community library), exported via the Figma MCP.
// Vector data is verbatim; only hardcoded black paint became currentColor.

import type { CSSProperties } from "react";

export interface IconProps {
  /** Rendered square size in px. Icons keep their own aspect ratio. */
  size?: number;
  className?: string;
  style?: CSSProperties;
  /** Supply only when the icon carries meaning on its own. */
  title?: string;
}

export function AlertIcon(props: IconProps) {
  return (
    <svg
      viewBox="0 0 21.793 20.976"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden={props.title ? undefined : true}
      role={props.title ? "img" : undefined}
      width={props.size ?? 20}
      height={props.size ?? 20}
      className={props.className}
      style={{ flexShrink: 0, ...props.style }}
    >
      {props.title ? <title>{props.title}</title> : null}
      <path d="M10.4633 7.80919V12.8092M10.4633 15.8092H10.4733M3.00391 19.976L18.7887 19.9757C20.3131 19.9757 21.277 18.3386 20.5376 17.0056L12.231 2.02991C11.4504 0.622501 9.41172 0.666649 8.69272 2.10653L1.21454 17.0825C0.550535 18.4123 1.51758 19.976 3.00391 19.976Z" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
    </svg>
  );
}

export function CalendarIcon(props: IconProps) {
  return (
    <svg
      viewBox="0 0 20 22"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden={props.title ? undefined : true}
      role={props.title ? "img" : undefined}
      width={props.size ?? 20}
      height={props.size ?? 20}
      className={props.className}
      style={{ flexShrink: 0, ...props.style }}
    >
      {props.title ? <title>{props.title}</title> : null}
      <path d="M6 1V5M14 1V5M1 9H19M5.8 21H14.2C15.8802 21 16.7202 21 17.362 20.673C17.9265 20.3854 18.3854 19.9265 18.673 19.362C19 18.7202 19 17.8802 19 16.2V7.8C19 6.11984 19 5.27976 18.673 4.63803C18.3854 4.07354 17.9265 3.6146 17.362 3.32698C16.7202 3 15.8802 3 14.2 3H5.8C4.11984 3 3.27976 3 2.63803 3.32698C2.07354 3.6146 1.6146 4.07354 1.32698 4.63803C1 5.27976 1 6.11984 1 7.8V16.2C1 17.8802 1 18.7202 1.32698 19.362C1.6146 19.9265 2.07354 20.3854 2.63803 20.673C3.27976 21 4.11984 21 5.8 21Z" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
    </svg>
  );
}

export function ChartIcon(props: IconProps) {
  return (
    <svg
      viewBox="0 0 20 20"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden={props.title ? undefined : true}
      role={props.title ? "img" : undefined}
      width={props.size ?? 20}
      height={props.size ?? 20}
      className={props.className}
      style={{ flexShrink: 0, ...props.style }}
    >
      {props.title ? <title>{props.title}</title> : null}
      <path d="M19 19H5.8C4.11984 19 3.27976 19 2.63803 18.673C2.07354 18.3854 1.6146 17.9265 1.32698 17.362C1 16.7202 1 15.8802 1 14.2V1M5 15V13M13 15V7M9 15V10M17 15V4" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
    </svg>
  );
}

export function CheckIcon(props: IconProps) {
  return (
    <svg
      viewBox="0 0 18 13"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden={props.title ? undefined : true}
      role={props.title ? "img" : undefined}
      width={props.size ?? 20}
      height={props.size ?? 20}
      className={props.className}
      style={{ flexShrink: 0, ...props.style }}
    >
      {props.title ? <title>{props.title}</title> : null}
      <path d="M1 6.5L6.33333 12L17 1" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
    </svg>
  );
}

export function ChevronRightIcon(props: IconProps) {
  return (
    <svg
      viewBox="0 0 8 14"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden={props.title ? undefined : true}
      role={props.title ? "img" : undefined}
      width={props.size ?? 20}
      height={props.size ?? 20}
      className={props.className}
      style={{ flexShrink: 0, ...props.style }}
    >
      {props.title ? <title>{props.title}</title> : null}
      <path d="M1 1L7 7L1 13" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
    </svg>
  );
}

export function FileIcon(props: IconProps) {
  return (
    <svg
      viewBox="0 0 18.0001 22.0001"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden={props.title ? undefined : true}
      role={props.title ? "img" : undefined}
      width={props.size ?? 20}
      height={props.size ?? 20}
      className={props.className}
      style={{ flexShrink: 0, ...props.style }}
    >
      {props.title ? <title>{props.title}</title> : null}
      <path d="M11 1.00006V5.50006C11 6.32848 11.6716 7.00006 12.5 7.00006H17M9.13288 1.00006H5.8C4.11984 1.00006 3.27976 1.00006 2.63803 1.32704C2.07354 1.61466 1.6146 2.0736 1.32698 2.63808C1 3.27982 1 4.1199 1 5.80006V16.2001C1 17.8802 1 18.7203 1.32698 19.362C1.6146 19.9265 2.07354 20.3855 2.63803 20.6731C3.27976 21.0001 4.11984 21.0001 5.8 21.0001H12.2C13.8802 21.0001 14.7202 21.0001 15.362 20.6731C15.9265 20.3855 16.3854 19.9265 16.673 19.362C17 18.7203 17 17.8802 17 16.2001V8.61158C17 7.83376 17 7.44485 16.9077 7.08146C16.826 6.75938 16.6912 6.45312 16.5091 6.1752C16.3035 5.86164 16.0169 5.59884 15.4435 5.07324L12.3764 2.26172C11.8675 1.79527 11.6131 1.56205 11.322 1.39565C11.0639 1.24808 10.7853 1.1397 10.4953 1.07407C10.1683 1.00006 9.82317 1.00006 9.13288 1.00006Z" stroke="currentColor" strokeWidth="2"/>
    </svg>
  );
}

export function MicrophoneIcon(props: IconProps) {
  return (
    <svg
      viewBox="0 0 16 22"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden={props.title ? undefined : true}
      role={props.title ? "img" : undefined}
      width={props.size ?? 20}
      height={props.size ?? 20}
      className={props.className}
      style={{ flexShrink: 0, ...props.style }}
    >
      {props.title ? <title>{props.title}</title> : null}
      <path d="M8 17C4.13401 17 1 13.866 1 10M8 17C11.866 17 15 13.866 15 10M8 17V21M8 21H12M8 21H4M8 13C6.34315 13 5 11.6569 5 10V4C5 2.34315 6.34315 1 8 1C9.65685 1 11 2.34315 11 4V10C11 11.6569 9.65685 13 8 13Z" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
    </svg>
  );
}

export function XIcon(props: IconProps) {
  return (
    <svg
      viewBox="0 0 14 14"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden={props.title ? undefined : true}
      role={props.title ? "img" : undefined}
      width={props.size ?? 20}
      height={props.size ?? 20}
      className={props.className}
      style={{ flexShrink: 0, ...props.style }}
    >
      {props.title ? <title>{props.title}</title> : null}
      <path d="M1 1L7 7M7 7L13 13M7 7L13 1M7 7L1 13" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/>
    </svg>
  );
}
