// Generates src/components/icons.tsx from the exported Hue SVGs in
// public/icons. The vector data is copied verbatim — only the hardcoded
// black paint is swapped for currentColor so icons can take theme colours.
//
// Re-run after adding an SVG:  node scripts/build-icons.mjs

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const SRC = "public/icons";
const OUT = "src/components/icons.tsx";

const pascal = (name) =>
  name
    .split(/[-_]/)
    .map((p) => p[0].toUpperCase() + p.slice(1))
    .join("");

const files = readdirSync(SRC).filter((f) => f.endsWith(".svg")).sort();

const components = files.map((file) => {
  const raw = readFileSync(join(SRC, file), "utf8");
  const viewBox = raw.match(/viewBox="([^"]+)"/)?.[1];
  if (!viewBox) throw new Error(`${file}: no viewBox`);

  // inner markup, with black paint made themeable
  const inner = raw
    .replace(/^[\s\S]*?<svg[^>]*>/, "")
    .replace(/<\/svg>\s*$/, "")
    .replace(/stroke="black"/g, 'stroke="currentColor"')
    .replace(/fill="black"/g, 'fill="currentColor"')
    .replace(/\sid="[^"]*"/g, "")
    .replace(/stroke-width=/g, "strokeWidth=")
    .replace(/stroke-linecap=/g, "strokeLinecap=")
    .replace(/stroke-linejoin=/g, "strokeLinejoin=")
    .replace(/fill-rule=/g, "fillRule=")
    .replace(/clip-rule=/g, "clipRule=")
    .trim();

  const name = pascal(file.replace(/\.svg$/, ""));
  return `export function ${name}Icon(props: IconProps) {
  return (
    <svg
      viewBox="${viewBox}"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden={props.title ? undefined : true}
      role={props.title ? "img" : undefined}
      width={props.size ?? 20}
      height={props.size ?? 20}
      className={props.className}
      style={{ flexShrink: 0, ...props.style }}
    >
      {props.title ? <title>{props.title}</title> : null}
      ${inner}
    </svg>
  );
}`;
});

const out = `// GENERATED by scripts/build-icons.mjs — do not edit by hand.
// Source: Hue Icons (Figma community library), exported via the Figma MCP.
// Vector data is verbatim; only hardcoded black paint became currentColor.

import type { CSSProperties } from "react";

export interface IconProps {
  /** Rendered square size in px. Icons keep their own aspect ratio. */
  size?: number;
  className?: string;
  style?: CSSProperties;
  /** Supply only when the icon carries meaning on its own. */
  title?: string;
}

${components.join("\n\n")}
`;

writeFileSync(OUT, out);
console.log(`wrote ${OUT} with ${files.length} icons: ${files.join(", ")}`);
